# Generated by Django 6.0.4 on 2026-05-05 08:54

import miclat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiclatData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=miclat.models.generate_code, max_length=100, unique=True)),
                ('nin', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('sexe', models.CharField(blank=True, max_length=10, null=True)),
                ('acteN', models.CharField(blank=True, max_length=10, null=True)),
                ('annee', models.CharField(blank=True, max_length=6, null=True)),
                ('nom_a', models.CharField(blank=True, max_length=50, null=True)),
                ('nom_f', models.CharField(blank=True, max_length=50, null=True)),
                ('d_nais', models.CharField(blank=True, max_length=30, null=True)),
                ('h_nais', models.CharField(blank=True, max_length=10, null=True)),
                ('pren_a', models.CharField(blank=True, max_length=50, null=True)),
                ('pren_f', models.CharField(blank=True, max_length=50, null=True)),
                ('presume', models.CharField(blank=True, max_length=10, null=True)),
                ('codecomm', models.CharField(blank=True, max_length=10, null=True)),
                ('nom_mere', models.CharField(blank=True, max_length=50, null=True)),
                ('lieu_nais', models.CharField(blank=True, max_length=50, null=True)),
                ('pren_mere', models.CharField(blank=True, max_length=50, null=True)),
                ('pren_pere', models.CharField(blank=True, max_length=50, null=True)),
                ('decesMentions', models.CharField(blank=True, max_length=5, null=True)),
                ('divorceMentions', models.CharField(blank=True, max_length=5, null=True)),
                ('mariageMentions', models.CharField(blank=True, max_length=5, null=True)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_in', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MiclatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=miclat.models.generate_code, max_length=100, unique=True)),
                ('nin', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('ERROR', 'Error')], max_length=10)),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_in', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
