# Generated by Django 6.0.4 on 2026-05-05 08:52

import django.db.models.deletion
import root.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=root.models.generate_code, max_length=20, unique=True)),
                ('name_fr', models.CharField(blank=True, max_length=200, null=True)),
                ('name_ar', models.CharField(blank=True, max_length=200, null=True)),
                ('active', models.BooleanField(default=True)),
                ('insert_in', models.DateTimeField(auto_now_add=True)),
                ('updated_in', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=root.models.generate_code, max_length=20, unique=True)),
                ('name_fr', models.CharField(blank=True, max_length=200, null=True)),
                ('name_ar', models.CharField(blank=True, max_length=200, null=True)),
                ('active', models.BooleanField(default=True)),
                ('insert_in', models.DateTimeField(auto_now_add=True)),
                ('updated_in', models.DateTimeField(auto_now=True)),
                ('commune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='wilayas', to='root.commune')),
            ],
        ),
        migrations.CreateModel(
            name='Registered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=root.models.generate_code, max_length=20, unique=True)),
                ('nin', models.CharField(blank=True, max_length=200, null=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('birthday', models.DateField(blank=True, default=None, null=True)),
                ('phone', models.CharField(blank=True, max_length=500, null=True)),
                ('miclat', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('insert_in', models.DateTimeField(auto_now_add=True)),
                ('updated_in', models.DateTimeField(auto_now=True)),
                ('wilaya', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='registered_people', to='root.wilaya')),
            ],
        ),
    ]
