# Generated by Django 6.0.4 on 2026-05-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registered',
            name='status',
            field=models.CharField(blank=True, choices=[('in_progress_nin', 'Check NIN'), ('verified', 'Verified')], default='in_progress_nin', max_length=100, null=True),
        ),
    ]
