# Generated by Django 6.0.4 on 2026-05-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_registered_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registered',
            name='status',
            field=models.CharField(blank=True, choices=[('check_nin', 'Check NIN'), ('verified', 'Verified'), ('failed', 'Failed')], default='check_nin', max_length=100, null=True),
        ),
    ]
