# Generated by Django 6.0.4 on 2026-05-05 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_alter_registered_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wilaya',
            name='commune',
        ),
        migrations.AddField(
            model_name='commune',
            name='wilaya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='wilayas', to='root.wilaya'),
        ),
    ]
