# Generated by Django 6.0.4 on 2026-05-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0004_remove_wilaya_commune_commune_wilaya'),
    ]

    operations = [
        migrations.AddField(
            model_name='registered',
            name='genre',
            field=models.CharField(blank=True, choices=[('', 'Select/ اختر'), ('m', 'Male/ ذكر'), ('f', 'Female/ أنثى')], default='m', max_length=20, null=True),
        ),
    ]
