# Generated by Django 6.0.4 on 2026-05-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0005_registered_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commune',
            name='code',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='wilaya',
            name='code',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
