# Generated by Django 6.0.4 on 2026-05-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0006_alter_commune_code_alter_wilaya_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registered',
            name='birthday',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='registered',
            name='nin',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='registered',
            name='phone',
            field=models.CharField(max_length=500),
        ),
    ]
