# Generated by Django 6.0.4 on 2026-05-05 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0007_alter_registered_birthday_alter_registered_nin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compagnion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200, unique=True)),
                ('nin', models.CharField(blank=True, max_length=200, null=True)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('genre', models.CharField(blank=True, choices=[('', 'Select/ اختر'), ('m', 'Male/ ذكر'), ('f', 'Female/ أنثى')], default='m', max_length=20, null=True)),
                ('birthday', models.DateField(blank=True, default=None, null=True)),
                ('phone', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='registered',
            name='birthday',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='registered',
            name='genre',
            field=models.CharField(choices=[('', 'Select/ اختر'), ('m', 'Male/ ذكر'), ('f', 'Female/ أنثى')], default='m', max_length=20),
        ),
        migrations.AlterField(
            model_name='registered',
            name='wilaya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='registered_people', to='root.wilaya'),
        ),
    ]
