# Generated by Django 6.0.4 on 2026-05-05 12:20

import django.utils.timezone
import root.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0008_compagnion_alter_registered_birthday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compagnion',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='compagnion',
            name='insert_in',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compagnion',
            name='updated_in',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='compagnion',
            name='code',
            field=models.CharField(default=root.models.generate_code_int, max_length=200, unique=True),
        ),
    ]
