# Generated by Django 6.0.4 on 2026-05-05 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0009_compagnion_active_compagnion_insert_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registered',
            name='birthday',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='registered',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='registered',
            name='genre',
            field=models.CharField(blank=True, choices=[('', 'Select/ اختر'), ('m', 'Male/ ذكر'), ('f', 'Female/ أنثى')], default='m', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='registered',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='registered',
            name='nin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='registered',
            name='phone',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='registered',
            name='wilaya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='registered_people', to='root.wilaya'),
        ),
    ]
