# Generated by Django 6.0.4 on 2026-05-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0010_alter_registered_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registered',
            name='nin',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
