# Generated by Django 6.0.4 on 2026-05-05 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0011_alter_registered_nin'),
    ]

    operations = [
        migrations.AddField(
            model_name='registered',
            name='compagnion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='root.compagnion'),
        ),
    ]
