# Generated by Django 6.0.4 on 2026-05-05 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0012_registered_compagnion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compagnion',
            name='email',
        ),
        migrations.RemoveField(
            model_name='compagnion',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='compagnion',
            name='last_name',
        ),
        migrations.AddField(
            model_name='compagnion',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
