# Generated by Django 6.0.4 on 2026-05-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0013_remove_compagnion_email_remove_compagnion_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registered',
            name='attestation_file',
            field=models.FileField(blank=True, null=True, upload_to='attestations/'),
        ),
    ]
