# Generated by Django 6.0.4 on 2026-05-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0016_contact_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_page', models.BooleanField(default=False)),
                ('registration', models.BooleanField(default=True)),
                ('email_notif', models.BooleanField(default=False)),
                ('update_in', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
